# Generated by Django 3.2.8 on 2021-10-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
